export const FormConfig = [
  {
    id: '#1-1',
    label: 'IP地址',
    name: 'ip',
    component: 'Input',
    placeholder: '',
    notes: '',
    rules: [],
    props: {},
    componentProps: {},
  },
  {
    id: '#2-1',
    label: '连接端口',
    name: 'port',
    component: 'InputNumber',
    placeholder: '',
    notes: '',
    rules: [],
    props: {},
    componentProps: {},
  },
  {
    id: '#3-1',
    label: '用户名',
    name: 'username',
    component: 'Input',
    placeholder: '',
    notes: '',
    rules: [],
    props: {},
    componentProps: {},
  },
  {
    id: '#4-1',
    label: '主机密码',
    name: 'password',
    component: 'Input',
    placeholder: '',
    notes: '',
    rules: [],
    props: {},
    componentProps: {},
  },
  {
    id: '#5-1',
    label: '配置文件路径',
    name: 'profile',
    component: 'Input',
    placeholder: '',
    notes: '',
    rules: [],
    props: {},
    componentProps: {},
  },
]
export const layout = {
  labelCol: { span: 4 },
  wrapperCol: { span: 8 },
}
export const initialValues = {
  port: 22,
}
