export const FormConfig = [
  {
    id: '#1-1',
    label: 'IP地址',
    name: 'IP',
    component: 'Input',
    placeholder: '',
    notes: '',
    rules: [],
    props: {},
    componentProps: {},
  },
  {
    id: '#2-1',
    label: '安装路径',
    name: 'installation',
    component: 'Input',
    placeholder: '',
    notes: '',
    rules: [],
    props: {},
    componentProps: {},
  },
  {
    id: '#3-1',
    label: 'JDK路径',
    name: 'JDK',
    component: 'Input',
    placeholder: '',
    notes: '',
    rules: [],
    props: {},
    componentProps: {},
  },
  {
    id: '#4-1',
    label: '用户名',
    name: 'username',
    component: 'Input',
    placeholder: '',
    notes: '',
    rules: [],
    props: {},
    componentProps: {},
  },
  {
    id: '#5-1',
    label: '主机密码',
    name: 'password',
    component: 'Input',
    placeholder: '',
    notes: '',
    rules: [],
    props: {},
    componentProps: {},
  },
]

export const layout = {
  labelCol: { span: 4 },
  wrapperCol: { span: 8 },
}
